apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: {###PROVIDE_YOUR_DIR_SHARED_NFS_SERVER_HERE###}
    server: {###PROVIDE_YOUR_IP_NFS_SERVER_HERE###}
  persistentVolumeReclaimPolicy: Retain
