apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocp-pvc-nfs
  namespace: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: ocp-pv-nfs
  storageClassName: ""
