apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: {###PROVIDE_YOUR_OPERATOR_PRODUCT_CP4X_HERE###}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv
  storageClassName: ""
