apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp-pv-nfs
  namespace: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: {###PROVIDE_YOUR_DIR_SHARED_NFS_SERVER_HERE###}
    server: {###PROVIDE_YOUR_IP_NFS_SERVER_HERE###}
  persistentVolumeReclaimPolicy: Retain
